### ISSUE TITLE
Development setup failing

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#161]
`./bin/rails db:setup` is failing with following error message. 

```
-- add_foreign_key("urls", "organizations")
   -> 0.0016s
rails aborted!
Faraday::ConnectionFailed: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
/Users/neerajsingh/code/acehelp-projects/acehelp/db/seeds.rb:14:in `<main>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/rails:17:in `<top (required)>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/spring:16:in `<top (required)>'
./bin/rails:11:in `load'
./bin/rails:11:in `<main>'

Caused by:
Errno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
/Users/neerajsingh/code/acehelp-projects/acehelp/db/seeds.rb:14:in `<main>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/rails:17:in `<top (required)>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/spring:16:in `<top (required)>'
./bin/rails:11:in `load'
./bin/rails:11:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 9200
/Users/neerajsingh/code/acehelp-projects/acehelp/db/seeds.rb:14:in `<main>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/rails:17:in `<top (required)>'
/Users/neerajsingh/code/acehelp-projects/acehelp/bin/spring:16:in `<top (required)>'
./bin/rails:11:in `load'
./bin/rails:11:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

I think it is because of https://github.com/bigbinary/acehelp/blob/ae7d0be6c6cf1a5f44b57afa46b2f36a1c585f09/app/models/article.rb#L4 

Please update README with what the fix is.

**Comment by vipulnsward** [comment]
I have made some changes at https://github.com/bigbinary/acehelp/commit/ae6a4c9ccb7fc5706a753b068d6dddec36ac8a40 to address this. Will update more
