### ISSUE TITLE
Fix the error in running migrations from scratch

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [bigbinary/acehelp#218]
``` 
PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_d7b9ff90af" cannot be implemented
DETAIL:  Key columns "organization_id" and "id" are of incompatible types: uuid and bigint.
: ALTER TABLE "users" ADD CONSTRAINT "fk_rails_d7b9ff90af"
FOREIGN KEY ("organization_id")
  REFERENCES "organizations" ("id")
/Users/prathamesh/Projects/BigBinary/acehelp/db/migrate/20180629152054_add_email_to_organizations_and_organization_id_to_users.rb:7:in `up'
-e:1:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_d7b9ff90af" cannot be implemented
DETAIL:  Key columns "organization_id" and "id" are of incompatible types: uuid and bigint.
: ALTER TABLE "users" ADD CONSTRAINT "fk_rails_d7b9ff90af"
FOREIGN KEY ("organization_id")
  REFERENCES "organizations" ("id")
/Users/prathamesh/Projects/BigBinary/acehelp/db/migrate/20180629152054_add_email_to_organizations_and_organization_id_to_users.rb:7:in `up'
-e:1:in `<main>'

Caused by:
PG::DatatypeMismatch: ERROR:  foreign key constraint "fk_rails_d7b9ff90af" cannot be implemented
DETAIL:  Key columns "organization_id" and "id" are of incompatible types: uuid and bigint.
/Users/prathamesh/Projects/BigBinary/acehelp/db/migrate/20180629152054_add_email_to_organizations_and_organization_id_to_users.rb:7:in `up'
-e:1:in `<main>'
Tasks: TOP => setup => db:migrate
```

@tejaswinichile _a

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki It works well when we call `rake db:setup` as we have set UUID in schema file.
To fix the above problem I need to update all migrations. Will that be okay?

**Comment by prathamesh-sonpatki** [comment]
yes
